INSERT INTO users (first_name, last_name, email, password, role, enabled) VALUES
('Karol', 'Kowalski', 'admin@gmail.com', '$2a$10$x8/dfybxxUa/03Q2iJ2cV.fimlccHQVDG7pxkkOTtv0A3Y/NSAiGO', 'ROLE_ADMIN', true);

INSERT INTO companies (name, country, city, street_address) VALUES ('Lazzy', 'France', 'Annecy', '3727 Boyd Crossing');
INSERT INTO companies (name, country, city, street_address) VALUES ('Npath', 'France', 'Albi', '24 Maple Place');
INSERT INTO companies (name, country, city, street_address) VALUES ('Quinu', 'France', 'Futuroscope', '0 La Follette Road');
INSERT INTO companies (name, country, city, street_address) VALUES ('Eare', 'France', 'Mende', '3776 Prentice Junction');
INSERT INTO companies (name, country, city, street_address) VALUES ('Aimbo', 'France', 'Paris 02', '5 Bonner Drive');
INSERT INTO companies (name, country, city, street_address) VALUES ('Shufflester', 'France', 'Blaye', '6 Granby Point');
INSERT INTO companies (name, country, city, street_address) VALUES ('Jayo', 'France', 'Le Mans', '2 Ramsey Crossing');
INSERT INTO companies (name, country, city, street_address) VALUES ('Rhycero', 'France', 'Marseille', '41 Victoria Court');
INSERT INTO companies (name, country, city, street_address) VALUES ('Skippad', 'Poland', 'Sosnie', '57346 Summer Ridge Way');
INSERT INTO companies (name, country, city, street_address) VALUES ('Youspan', 'France', 'Avignon', '5 Hagan Street');
INSERT INTO companies (name, country, city, street_address) VALUES ('InnoZ', 'Poland', 'Bobowa', '8781 Talisman Hill');
INSERT INTO companies (name, country, city, street_address) VALUES ('Youtags', 'Poland', 'Klomnice', '49 East Center');
INSERT INTO companies (name, country, city, street_address) VALUES ('Brainverse', 'Germany', 'Berlin', '81 Claremont Drive');
INSERT INTO companies (name, country, city, street_address) VALUES ('Trupe', 'France', 'Le Havre', '683 Alpine Pass');
INSERT INTO companies (name, country, city, street_address) VALUES ('Topicware', 'Poland', 'Swiecie nad Osa', '74381 Knutson Crossing');
INSERT INTO companies (name, country, city, street_address) VALUES ('Centizu', 'France', 'Orleans', '520 Oxford Trail');
INSERT INTO companies (name, country, city, street_address) VALUES ('Mynte', 'Poland', 'Jelcz', '73 Ridge Oak Place');
INSERT INTO companies (name, country, city, street_address) VALUES ('Gevee', 'Poland', 'Debow', '44332 Kim Way');
INSERT INTO companies (name, country, city, street_address) VALUES ('Trunyx', 'France', 'Orleans', '749 Surrey Terrace');
INSERT INTO companies (name, country, city, street_address) VALUES ('Aimbo', 'Poland', 'Gizalki', '89 Forest Dale Court');

insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Lincoln', 'Continental', 1998, 'Turquoise', 382, null, true, 19, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Pontiac', 'Montana', 2000, 'Blue', 218, null, true, 6, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Maybach', 'Landaulet', 2011, 'Red', 159, null, true, 13, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Geo', 'Tracker', 1994, 'Indigo', 72, null, true, 8, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Kia', 'Spectra', 2007, 'Yellow', 74, null, true, 19, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Oldsmobile', 'Intrigue', 1999, 'Green', 374, null, true, 10, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Lotus', 'Elan', 1990, 'Indigo', 387, null, true, 8, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Audi', '90', 1990, 'Teal', 339, null, true, 16, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Toyota', 'Camry Hybrid', 2009, 'Goldenrod', 126, null, true, 13, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Mercury', 'Grand Marquis', 1994, 'Maroon', 89, null, true, 4, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Ford', 'Tempo', 1984, 'Turquoise', 155, null, true, 16, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Buick', 'Regal', 2004, 'Fuscia', 360, null, true, 6, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Chrysler', 'Sebring', 2010, 'Crimson', 324, null, true, 7, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Ford', 'Taurus', 2003, 'Violet', 138, null, true, 2, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Suzuki', 'Aerio', 2007, 'Maroon', 297, null, true, 9, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Chevrolet', 'Express 3500', 2008, 'Yellow', 171, null, true, 19, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Ford', 'Excursion', 2002, 'Green', 341, null, true, 2, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Chevrolet', 'Tracker', 2000, 'Mauv', 60, null, true, 2, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Dodge', 'Ram 3500', 2007, 'Red', 143, null, true, 17, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Eagle', 'Talon', 1991, 'Maroon', 212, null, true, 16, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('GMC', '1500', 1994, 'Indigo', 386, null, true, 8, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Audi', 'A3', 2007, 'Teal', 122, null, true, 5, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Dodge', 'Ram Van 3500', 1997, 'Yellow', 306, null, true, 8, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Hyundai', 'Elantra', 2006, 'Puce', 145, null, true, 13, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Honda', 'Ridgeline', 2009, 'Blue', 372, null, true, 16, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Buick', 'Regal', 1989, 'Crimson', 114, null, true, 14, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Chrysler', '300M', 2001, 'Purple', 353, null, true, 15, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Land Rover', 'Discovery', 2012, 'Khaki', 229, null, true, 14, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Infiniti', 'M', 1992, 'Crimson', 62, null, true, 17, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Toyota', 'Previa', 1995, 'Fuscia', 299, null, true, 11, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Pontiac', 'LeMans', 1988, 'Blue', 146, null, true, 13, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Volvo', 'S60', 2012, 'Blue', 68, null, true, 19, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('BMW', 'M6', 2010, 'Aquamarine', 279, null, true, 5, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Acura', 'SLX', 1998, 'Violet', 292, null, true, 10, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Bentley', 'Continental', 2010, 'Blue', 389, null, true, 17, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Audi', 'TT', 2000, 'Teal', 151, null, true, 9, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('GMC', 'Canyon', 2009, 'Purple', 152, null, true, 3, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Lincoln', 'Town Car', 1991, 'Green', 173, null, true, 10, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Subaru', 'Brat', 1985, 'Yellow', 275, null, true, 2, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('GMC', 'Sierra Hybrid', 2006, 'Orange', 131, null, true, 4, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Saturn', 'Relay', 2006, 'Aquamarine', 103, null, true, 1, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Mercury', 'Cougar', 1990, 'Puce', 79, null, true, 15, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Acura', 'RDX', 2010, 'Puce', 351, null, true, 3, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Ford', 'F250', 1998, 'Yellow', 200, null, true, 19, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Nissan', 'Pathfinder', 2003, 'Maroon', 205, null, true, 13, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Suzuki', 'Esteem', 2000, 'Crimson', 191, null, true, 15, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Ford', 'F350', 1993, 'Goldenrod', 75, null, true, 18, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Toyota', 'Celica', 1995, 'Yellow', 378, null, true, 15, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Jeep', 'Compass', 2010, 'Fuscia', 231, null, true, 6, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Mercury', 'Sable', 1994, 'Fuscia', 108, null, true, 4, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Hyundai', 'Accent', 1997, 'Teal', 92, null, true, 9, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Subaru', 'BRZ', 2013, 'Violet', 376, null, true, 7, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Jaguar', 'XK', 2010, 'Pink', 295, null, true, 7, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Bentley', 'Continental', 2008, 'Blue', 62, null, true, 14, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Oldsmobile', 'Bravada', 2002, 'Goldenrod', 394, null, true, 15, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('GMC', 'Yukon', 1994, 'Yellow', 342, null, true, 12, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Plymouth', 'Neon', 2000, 'Orange', 388, null, true, 9, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Ford', 'F250', 2012, 'Violet', 118, null, true, 20, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Chevrolet', '3500', 1993, 'Teal', 193, null, true, 2, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Cadillac', 'Escalade ESV', 2009, 'Maroon', 380, null, true, 16, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Lincoln', 'Navigator', 2001, 'Turquoise', 104, null, true, 5, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Volvo', 'S90', 1998, 'Pink', 220, null, true, 19, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Chevrolet', 'Caprice', 1994, 'Purple', 76, null, true, 5, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Chevrolet', 'Corvette', 2004, 'Khaki', 302, null, true, 13, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Buick', 'LeSabre', 2004, 'Mauv', 70, null, true, 15, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Ford', 'Bronco', 1993, 'Blue', 224, null, true, 13, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Lexus', 'IS-F', 2010, 'Green', 229, null, true, 5, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Mercedes-Benz', '500SEL', 1992, 'Mauv', 141, null, true, 7, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Mercedes-Benz', '400E', 1992, 'Crimson', 272, null, true, 6, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Chrysler', 'Sebring', 2001, 'Violet', 88, null, true, 3, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Aston Martin', 'DBS', 2011, 'Yellow', 170, null, true, 2, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Lincoln', 'Town Car', 1996, 'Crimson', 294, null, true, 11, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Honda', 'Element', 2010, 'Indigo', 226, null, true, 20, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Dodge', 'Avenger', 2009, 'Turquoise', 51, null, true, 8, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('GMC', 'Sierra', 2008, 'Fuscia', 93, null, true, 2, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Scion', 'tC', 2013, 'Fuscia', 180, null, true, 20, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Ford', 'Explorer', 2009, 'Indigo', 262, null, true, 8, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Volvo', 'XC70', 2006, 'Goldenrod', 357, null, true, 7, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Toyota', '4Runner', 1993, 'Red', 151, null, true, 10, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Dodge', 'Ram 1500', 2007, 'Red', 171, null, true, 17, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Ford', 'Windstar', 2004, 'Fuscia', 272, null, true, 6, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Nissan', '240SX', 1992, 'Maroon', 57, null, true, 13, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Lincoln', 'Town Car', 2009, 'Aquamarine', 137, null, true, 8, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Chevrolet', 'Colorado', 2010, 'Maroon', 104, null, true, 3, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Suzuki', 'SX4', 2007, 'Goldenrod', 224, null, true, 18, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Chevrolet', 'Avalanche 1500', 2006, 'Red', 314, null, true, 16, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('GMC', 'Sierra 2500', 2004, 'Goldenrod', 329, null, true, 4, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Mitsubishi', 'Mirage', 1988, 'Fuscia', 103, null, true, 14, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Cadillac', 'CTS', 2012, 'Indigo', 69, null, true, 3, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Chevrolet', 'Suburban 2500', 2002, 'Maroon', 205, null, true, 2, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Mercedes-Benz', 'SLK-Class', 1997, 'Blue', 122, null, true, 3, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Acura', 'Integra', 1996, 'Fuscia', 93, null, true, 9, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Chevrolet', 'Silverado 3500', 2008, 'Orange', 197, null, true, 7, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Subaru', 'XT', 1987, 'Mauv', 266, null, true, 7, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Acura', 'MDX', 2007, 'Mauv', 214, null, true, 2, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('GMC', 'Envoy XL', 2006, 'Maroon', 193, null, true, 13, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Geo', 'Prizm', 1992, 'Fuscia', 60, null, true, 9, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Pontiac', 'Grand Am', 1998, 'Turquoise', 110, null, true, 18, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Toyota', 'Tacoma Xtra', 2002, 'Yellow', 151, null, true, 4, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Ford', 'E-Series', 1963, 'Goldenrod', 54, null, true, 9, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('GMC', 'Savana 2500', 2002, 'Blue', 206, null, true, 16, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Subaru', 'Loyale', 1990, 'Violet', 175, null, true, 18, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Suzuki', 'Swift', 2004, 'Turquoise', 187, null, true, 10, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Jeep', 'Cherokee', 1998, 'Orange', 369, null, true, 12, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Nissan', 'Pathfinder', 2006, 'Orange', 235, null, true, 6, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Chevrolet', 'G-Series G20', 1995, 'Fuscia', 383, null, true, 3, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Hyundai', 'Accent', 1995, 'Turquoise', 94, null, true, 8, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Mercedes-Benz', 'CLK-Class', 1999, 'Goldenrod', 394, null, true, 1, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Ford', 'F-Series', 2007, 'Pink', 256, null, true, 9, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Chevrolet', 'Corvette', 1959, 'Yellow', 73, null, true, 5, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('BMW', 'M3', 2006, 'Mauv', 198, null, true, 1, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Land Rover', 'Discovery Series II', 2000, 'Crimson', 368, null, true, 11, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Saab', '9-4X', 2011, 'Aquamarine', 317, null, true, 19, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Toyota', '4Runner', 2001, 'Pink', 339, null, true, 9, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('BMW', 'M5', 2009, 'Orange', 222, null, true, 9, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Audi', 'S6', 2011, 'Blue', 143, null, true, 16, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Chevrolet', 'Suburban 2500', 2009, 'Puce', 245, null, true, 3, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Ford', 'LTD Crown Victoria', 1989, 'Indigo', 154, null, true, 19, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Mitsubishi', 'Eclipse', 2005, 'Turquoise', 181, null, true, 5, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Cadillac', 'Escalade ESV', 2011, 'Purple', 185, null, true, 5, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Pontiac', 'Firefly', 1987, 'Maroon', 165, null, true, 14, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Toyota', 'Land Cruiser', 2013, 'Crimson', 88, null, true, 12, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Volkswagen', 'Rabbit', 2010, 'Orange', 327, null, true, 3, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Mercury', 'Mountaineer', 2009, 'Orange', 268, null, true, 4, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('GMC', 'Sierra 1500', 2000, 'Mauv', 125, null, true, 18, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('GMC', 'Yukon XL 1500', 2012, 'Violet', 170, null, true, 18, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Bentley', 'Continental', 2009, 'Mauv', 283, null, true, 7, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Toyota', 'Sienna', 2011, 'Yellow', 104, null, true, 7, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Chevrolet', 'Volt', 2012, 'Puce', 259, null, true, 4, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Ford', 'Focus', 2011, 'Indigo', 202, null, true, 16, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Ford', 'E150', 2009, 'Green', 204, null, true, 7, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Chevrolet', 'Corvette', 1988, 'Crimson', 80, null, true, 2, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Oldsmobile', 'Silhouette', 2004, 'Goldenrod', 76, null, true, 3, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Mercury', 'Mountaineer', 1998, 'Puce', 95, null, true, 15, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Chevrolet', 'Cavalier', 2000, 'Khaki', 343, null, true, 18, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Ford', 'Mustang', 1969, 'Purple', 356, null, true, 19, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Suzuki', 'SJ', 1991, 'Pink', 239, null, true, 15, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Honda', 'Civic', 2011, 'Teal', 56, null, true, 20, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Ford', 'Explorer', 1996, 'Goldenrod', 373, null, true, 20, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Ford', 'Mustang', 1971, 'Turquoise', 116, null, true, 16, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Lexus', 'GX', 2008, 'Yellow', 56, null, true, 16, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Ford', 'F250', 1999, 'Mauv', 195, null, true, 5, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Pontiac', 'Trans Sport', 1999, 'Violet', 188, null, true, 17, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Mitsubishi', 'Montero Sport', 2001, 'Yellow', 190, null, true, 18, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Maserati', 'Quattroporte', 2009, 'Aquamarine', 360, null, true, 19, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Pontiac', 'Montana SV6', 2006, 'Green', 279, null, true, 8, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Honda', 'Civic', 1997, 'Pink', 291, null, true, 20, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Volkswagen', 'GTI', 1999, 'Purple', 191, null, true, 2, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Suzuki', 'Sidekick', 1996, 'Turquoise', 316, null, true, 14, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Ford', 'Thunderbird', 2006, 'Aquamarine', 74, null, true, 11, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Mazda', 'RX-8', 2004, 'Goldenrod', 163, null, true, 8, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Acura', 'SLX', 1999, 'Aquamarine', 336, null, true, 18, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Jeep', 'Grand Cherokee', 2006, 'Green', 323, null, true, 5, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Maserati', 'GranTurismo', 2010, 'Violet', 346, null, true, 9, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Mitsubishi', 'Diamante', 1997, 'Mauv', 351, null, true, 13, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Infiniti', 'G37', 2008, 'Indigo', 218, null, true, 15, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Buick', 'Century', 2003, 'Teal', 322, null, true, 2, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Lincoln', 'Town Car', 1993, 'Teal', 390, null, true, 10, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('BMW', 'M', 2000, 'Puce', 392, null, true, 2, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Mercedes-Benz', 'CLS-Class', 2007, 'Mauv', 250, null, true, 10, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Alfa Romeo', 'Spider', 1994, 'Teal', 311, null, true, 11, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Dodge', 'Charger', 1969, 'Fuscia', 342, null, true, 15, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Chrysler', 'Town & Country', 2008, 'Orange', 217, null, true, 13, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Ford', 'F-Series', 2008, 'Teal', 337, null, true, 10, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Volkswagen', 'Fox', 1988, 'Indigo', 207, null, true, 7, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Nissan', '350Z', 2005, 'Yellow', 198, null, true, 16, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Infiniti', 'QX56', 2009, 'Crimson', 144, null, true, 6, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Kia', 'Spectra', 2008, 'Crimson', 53, null, true, 2, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Land Rover', 'Freelander', 2004, 'Fuscia', 183, null, true, 14, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Volkswagen', 'GTI', 1990, 'Red', 115, null, true, 13, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('GMC', 'Savana 2500', 2012, 'Khaki', 211, null, true, 7, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Maybach', '57', 2007, 'Crimson', 302, null, true, 16, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Lotus', 'Evora', 2012, 'Violet', 296, null, true, 19, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Mercury', 'Grand Marquis', 1985, 'Teal', 116, null, true, 11, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Subaru', 'Impreza', 1999, 'Indigo', 194, null, true, 14, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Cadillac', 'Eldorado', 2002, 'Maroon', 225, null, true, 4, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Buick', 'Regal', 2002, 'Fuscia', 340, null, true, 7, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Mercedes-Benz', 'SL-Class', 2008, 'Aquamarine', 314, null, true, 10, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Chevrolet', 'Sportvan G10', 1993, 'Violet', 123, null, true, 4, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Maybach', '62', 2011, 'Maroon', 253, null, true, 11, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Nissan', 'Sentra', 1998, 'Green', 296, null, true, 19, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Chevrolet', 'Silverado 3500', 2002, 'Khaki', 124, null, true, 15, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Chevrolet', 'Venture', 2002, 'Crimson', 398, null, true, 19, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Pontiac', 'Sunfire', 2003, 'Red', 155, null, true, 12, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Infiniti', 'J', 1996, 'Teal', 121, null, true, 6, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Nissan', 'Xterra', 2006, 'Purple', 61, null, true, 12, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('GMC', 'Envoy XL', 2003, 'Turquoise', 201, null, true, 19, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Ford', 'Escape', 2011, 'Green', 148, null, true, 20, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Ford', 'Tempo', 1992, 'Purple', 179, null, true, 19, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Volkswagen', 'Passat', 2002, 'Teal', 332, null, true, 3, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Lexus', 'RX', 2011, 'Mauv', 281, null, true, 16, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('GMC', 'Savana 1500', 1997, 'Violet', 260, null, true, 17, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Mitsubishi', 'Mirage', 1985, 'Yellow', 268, null, true, 4, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('GMC', 'Sonoma', 1992, 'Aquamarine', 257, null, true, 11, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Chevrolet', 'Express 3500', 2002, 'Violet', 63, null, true, 16, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Ford', 'Probe', 1995, 'Fuscia', 89, null, true, 11, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Ford', 'Taurus', 1990, 'Mauv', 224, null, true, 7, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Jaguar', 'XJ Series', 1994, 'Maroon', 58, null, true, 20, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Kia', 'Sportage', 1998, 'Mauv', 110, null, true, 14, null);
insert into cars (brand, model, year, color, daily_fee, rent_date, available, company_id, user_id) values ('Chevrolet', 'G-Series G30', 1992, 'Crimson', 236, null, true, 3, null);